version: "3.5"

volumes:
  redis-data:
  
services:
  solr:
    image: solr:7.7.2
    container_name: solr
    entrypoint:
    - bash
    - "-c"
    - "precreate-core sdmx-facet-search; exec solr -f"
    networks:
      - dotstat_network
  
  redis:
    image: redis:5.0.3
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - dotstat_network

  proxy:
    image: siscc/dotstatsuite-kube-proxy:master
    container_name: proxy
    environment:
      CONFIG_URL: http://config
    ports:
      - "80:80"
    volumes:
      - "./config/routes.json:/opt/data/routes.json"
    networks:
      - dotstat_network

  config:
    image: siscc/dotstatsuite-config:master
    container_name: config
    volumes:
      - "./config/assets:/opt/assets"
      - "./config/configs:/opt/configs"
      - "./config/i18n:/opt/i18n"
    networks:
      - dotstat_network

  data-lifecycle-manager:
    image: siscc/dotstatsuite-data-lifecycle-manager:master
    container_name: data-lifecycle-manager
    environment:
      SERVER_PORT: 80
      DEFAULT_TENANT: ${DEFAULT_TENANT}
      CONFIG_URL: http://config
      AUTH_SERVER_URL: "${PROTOCOL}://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}"
      TRANSFER_SERVER_URL: "${PROTOCOL}://${HOST}:${TRANSFER_PORT}/${TRANSFER_API_VERSION}"
    networks:
      - dotstat_network

  data-explorer:
    image: siscc/dotstatsuite-data-explorer:master
    container_name: data-explorer
    environment:
      CONFIG_URL: http://config
      AUTH_SERVER_URL: "${PROTOCOL}://${HOST}:${KEYCLOAK_PORT}"
      AUTH_PROVIDER: ${AUTH_PROVIDER}
    networks:
      - dotstat_network

  share:
    image: siscc/dotstatsuite-share:master
    container_name: share
    environment:
      CONFIG_URL: http://config
      SITE_URL: http://share.localhost
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${SHARE_DB_INDEX}
      PORT: 80
    networks:
      - dotstat_network

  data-viewer:
    image: siscc/dotstatsuite-data-viewer:master
    container_name: data-viewer
    environment:
      CONFIG_URL: http://config
    networks:
      - dotstat_network

  sdmx-faceted-search:
    image: siscc/dotstatsuite-sdmx-faceted-search:master
    container_name: sdmx-faceted-search
    depends_on:
      - solr
    environment:
      SERVER_HOST: ${HOST}
      CONFIG_URL: http://config
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      SOLR_HOST: solr
      SOLR_PORT: ${SOLR_PORT}
      REDIS_DB: ${SFS_DB_INDEX}
    entrypoint:
      - sh
      - -c
      - "sleep 45s; yarn dist:run"
    networks:
      - dotstat_network

networks:
  dotstat_network:
    name: dotstat_common_network
