version: "3"

volumes:
  redis-data:
  solr-data:

services:
  solr:
    image: solr:8.7.0
    container_name: solr
    entrypoint: 
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
    ports:
      - "${SOLR_PORT}:8983"
    volumes: 
      - solr-data:/var/solr

  redis:
    image: redis:5.0.3
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data