version: "3"

volumes:
  mongo-data:
  solr-data:

services:
  solr:
    image: solr:8.7.0
    container_name: solr
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - solr-data:/var/solr

  mongo:
    image: mongo:5.0.6
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/configdb
